apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api-deployment
spec:
  selector:
    matchLabels:
      app: devops-api
      version: blue
  template:
    metadata:
      labels:
        app: devops-api
        version: blue
    spec:
      containers:
      - name: devops-api-container
        image: brunoverdaninfnet/apidevops:v1
        ports:
        - containerPort: 8080