apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api-deployment-green
spec:
  selector:
    matchLabels:
      app: devops-api
      version: green
  template:
    metadata:
      labels:
        app: devops-api
        version: green
    spec:
      containers:
      - name: devops-api-container
        image: brunoverdaninfnet/apidevops:v2
        ports:
        - containerPort: 8080