apiVersion: v1
kind: Service
metadata:
  name: devops-api-service-node
spec:
  type: NodePort
  selector:
    app: devops-api
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30002
---

apiVersion: v1
kind: Service
metadata:
  name: devops-api-service-cluster
spec:
  type: ClusterIP
  selector:
    app: devops-api
  ports:
    - port: 8080
      targetPort: 8080