apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
      - name: devops-api-container
        image: brunoverdaninfnet/apidevops:v4
        ports:
        - containerPort: 8080