apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api-canary-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-api-canary
  template:
    metadata:
      labels:
        app: devops-api-canary
    spec:
      containers:
      - name: devops-api-container
        image: brunoverdaninfnet/apidevops:v1
        ports:
        - containerPort: 8080