apiVersion: v1
kind: Service
metadata:
  name: grafana-service-node
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30003
---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service-cluster
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090