apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-node
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      nodePort: 30001
---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-cluster
spec:
  selector:
    app: prometheus
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090